# Generated by Django 4.1.1 on 2022-12-25 05:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/aquariums/')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sky',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/skies/')),
                ('folder', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('x', models.DecimalField(decimal_places=2, max_digits=30)),
                ('y', models.DecimalField(decimal_places=2, max_digits=30)),
                ('z', models.DecimalField(decimal_places=2, max_digits=30)),
                ('max_x', models.DecimalField(decimal_places=2, max_digits=30)),
                ('min_x', models.DecimalField(decimal_places=2, max_digits=30)),
                ('max_y', models.DecimalField(decimal_places=2, max_digits=30)),
                ('min_y', models.DecimalField(decimal_places=2, max_digits=30)),
                ('max_z', models.DecimalField(decimal_places=2, max_digits=30)),
                ('min_z', models.DecimalField(decimal_places=2, max_digits=30)),
                ('model', models.CharField(max_length=200)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.scene', to_field='name')),
            ],
        ),
    ]
