# Generated by Django 4.1.1 on 2022-12-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.scene', to_field='folder'),
        ),
    ]
