# Generated by Django 4.1.1 on 2022-12-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0003_alter_prop_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.scene', to_field='name'),
        ),
    ]
