# Generated by Django 4.1.1 on 2022-12-24 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish', '0001_initial'),
        ('aquarium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('aquarium', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='aquarium.aquarium')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaries', to=settings.AUTH_USER_MODEL)),
                ('fish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='fish.fish')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.mood')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.weather')),
            ],
        ),
    ]
