# Generated by Django 4.1.1 on 2022-12-25 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0001_initial'),
        ('aquarium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquarium',
            name='scene',
            field=models.ForeignKey(db_column='scene', null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.scene', to_field='folder'),
        ),
        migrations.AddField(
            model_name='aquarium',
            name='sky',
            field=models.ForeignKey(db_column='sky', null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.sky'),
        ),
    ]
